import { defineCommand } from "citty"
import { AGENT_JSON_HINT } from "../../args/output"

export default defineCommand({
  meta: {
    name: "agents",
    description: [
      "Configure Outlit agents.",
      "",
      "Commands:",
      "  list                          List configured agents",
      "  get <id>                      Get one configured agent",
      "  templates                     List available agent templates",
      "  actions                       List available agent configuration actions",
      "  create-from-template <template>",
      "                                Create a draft agent from a platform template",
      "  create-custom                 Create a custom hosted agent",
      "  update-profile <id>           Update an agent display profile",
      "  update-instructions <id>      Update custom agent instructions",
      "  update-actions <id>           Update custom agent action keys",
      "  enable <id>                   Enable a configured agent",
      "  disable <id>                  Disable a configured agent",
      "  rename <id> <display-name>    Rename a configured agent",
      "",
      "Examples:",
      "  outlit agents list --json",
      "  outlit agents get 10000000-0000-4000-8000-000000000004 --json",
      "  outlit agents templates --json",
      "  outlit agents actions --json",
      "  outlit agents create-from-template churn --json",
      "  outlit agents create-custom --display-name 'Renewal risk' --instructions 'Find risk' --surface-criteria 'Surface risky customers' --json",
      "  outlit agents update-profile 10000000-0000-4000-8000-000000000004 --display-name 'Renewal risk' --json",
      "  outlit agents update-instructions 10000000-0000-4000-8000-000000000004 --instructions 'New instructions' --json",
      "  outlit agents update-actions 10000000-0000-4000-8000-000000000004 --action-keys send_slack_notification --json",
      "  outlit agents update-actions 10000000-0000-4000-8000-000000000004 --clear --json",
      "  outlit agents enable 10000000-0000-4000-8000-000000000004 --json",
      "  outlit agents disable 10000000-0000-4000-8000-000000000004 --json",
      "  outlit agents rename 10000000-0000-4000-8000-000000000004 'Churn prevention' --json",
      "",
      AGENT_JSON_HINT,
    ].join("\n"),
  },
  subCommands: {
    list: () => import("./list").then((m) => m.default),
    get: () => import("./get").then((m) => m.default),
    templates: () => import("./templates").then((m) => m.default),
    actions: () => import("./actions").then((m) => m.default),
    "create-from-template": () => import("./create-from-template").then((m) => m.default),
    "create-custom": () => import("./create-custom").then((m) => m.default),
    "update-profile": () => import("./update-profile").then((m) => m.default),
    "update-instructions": () => import("./update-instructions").then((m) => m.default),
    "update-actions": () => import("./update-actions").then((m) => m.default),
    enable: () => import("./enable").then((m) => m.default),
    disable: () => import("./disable").then((m) => m.default),
    rename: () => import("./rename").then((m) => m.default),
  },
})
