import { defineCommand } from "citty"
import { AGENT_JSON_HINT } from "../../args/output"

export default defineCommand({
  meta: {
    name: "automations",
    description: [
      "Configure Outlit automations.",
      "",
      "Commands:",
      "  list                          List configured automations",
      "  get <id>                      Get one configured automation",
      "  runs                          Inspect automation runs",
      "  options                       Show automation schemas and constants",
      "  create                        Create an agent automation",
      "  update <id>                   Update an agent automation",
      "  enable <id>                   Enable a configured automation",
      "  disable <id>                  Disable a configured automation",
      "  archive <id>                  Archive a configured automation",
      "",
      "Examples:",
      "  outlit automations list --json",
      "  outlit automations get 10000000-0000-4000-8000-000000000001 --json",
      "  outlit automations runs list 10000000-0000-4000-8000-000000000001 --json",
      "  outlit automations options --json",
      "  outlit automations create --file ./automation.json --json",
      "  outlit automations update 10000000-0000-4000-8000-000000000001 --file ./automation.json --json",
      "  outlit automations enable 10000000-0000-4000-8000-000000000001 --json",
      "  outlit automations disable 10000000-0000-4000-8000-000000000001 --json",
      "  outlit automations archive 10000000-0000-4000-8000-000000000001 --json",
      "",
      AGENT_JSON_HINT,
    ].join("\n"),
  },
  subCommands: {
    list: () => import("./list").then((m) => m.default),
    get: () => import("./get").then((m) => m.default),
    runs: () => import("./runs").then((m) => m.default),
    options: () => import("./options").then((m) => m.default),
    create: () => import("./create").then((m) => m.default),
    update: () => import("./update").then((m) => m.default),
    enable: () => import("./enable").then((m) => m.default),
    disable: () => import("./disable").then((m) => m.default),
    archive: () => import("./archive").then((m) => m.default),
  },
})
